[package]
name = "aoc_2019_day3_part1"
version = "0.1.0"
authors = ["Vincent Palancher <vincent.palancher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
